# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '二阶界面.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class ThirdWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(15)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter_9 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_9.setGeometry(QtCore.QRect(440, 10, 251, 121))
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setObjectName("splitter_9")
        self.splitter_8 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.splitter_7 = QtWidgets.QSplitter(self.splitter_8)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName("splitter_7")
        self.label_5 = QtWidgets.QLabel(self.splitter_7)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.splitter_7)
        self.label_6.setObjectName("label_6")
        self.splitter_6 = QtWidgets.QSplitter(self.splitter_8)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.showT = QtWidgets.QLCDNumber(self.splitter_6)
        self.showT.setObjectName("showT")
        self.showF = QtWidgets.QLCDNumber(self.splitter_6)
        self.showF.setObjectName("showF")
        self.slideT = QtWidgets.QSlider(self.splitter_9)
        self.slideT.setOrientation(QtCore.Qt.Horizontal)
        self.slideT.setObjectName("slideT")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(410, 10, 20, 121))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.return_2 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.return_2.setGeometry(QtCore.QRect(720, 10, 71, 41))
        self.return_2.setObjectName("return_2")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(700, 10, 20, 121))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.splitter_14 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_14.setGeometry(QtCore.QRect(10, 10, 391, 121))
        self.splitter_14.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_14.setObjectName("splitter_14")
        self.splitter_12 = QtWidgets.QSplitter(self.splitter_14)
        self.splitter_12.setOrientation(QtCore.Qt.Vertical)
        self.splitter_12.setObjectName("splitter_12")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_12)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.label_7 = QtWidgets.QLabel(self.splitter_5)
        self.label_7.setObjectName("label_7")
        self.Rin_2 = QtWidgets.QLineEdit(self.splitter_5)
        self.Rin_2.setObjectName("Rin_2")
        self.splitter_10 = QtWidgets.QSplitter(self.splitter_12)
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName("splitter_10")
        self.label_8 = QtWidgets.QLabel(self.splitter_10)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.U0in_2 = QtWidgets.QLineEdit(self.splitter_10)
        self.U0in_2.setObjectName("U0in_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_12)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_4 = QtWidgets.QLabel(self.splitter)
        self.label_4.setObjectName("label_4")
        self.LCin = QtWidgets.QLineEdit(self.splitter)
        self.LCin.setObjectName("LCin")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_12)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.U0in = QtWidgets.QLineEdit(self.splitter_2)
        self.U0in.setObjectName("U0in")
        self.splitter_13 = QtWidgets.QSplitter(self.splitter_14)
        self.splitter_13.setOrientation(QtCore.Qt.Vertical)
        self.splitter_13.setObjectName("splitter_13")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_13)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_3 = QtWidgets.QLabel(self.splitter_4)
        self.label_3.setObjectName("label_3")
        self.Rin = QtWidgets.QLineEdit(self.splitter_4)
        self.Rin.setObjectName("Rin")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_13)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_2 = QtWidgets.QLabel(self.splitter_3)
        self.label_2.setObjectName("label_2")
        self.Uooin = QtWidgets.QLineEdit(self.splitter_3)
        self.Uooin.setObjectName("Uooin")
        self.splitter_11 = QtWidgets.QSplitter(self.splitter_13)
        self.splitter_11.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_11.setObjectName("splitter_11")
        self.draw = QtWidgets.QPushButton(self.splitter_11)
        self.draw.setObjectName("draw")
        self.clear = QtWidgets.QPushButton(self.splitter_11)
        self.clear.setObjectName("clear")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.menu.addAction(self.actionhelp)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "时间t："))
        self.label_6.setText(_translate("MainWindow", "电压U："))
        self.return_2.setText(_translate("MainWindow", "返回"))
        self.label_7.setText(_translate("MainWindow", "C"))
        self.label_8.setText(_translate("MainWindow", "I0"))
        self.label_4.setText(_translate("MainWindow", "L"))
        self.label.setText(_translate("MainWindow", "U0"))
        self.label_3.setText(_translate("MainWindow", "R"))
        self.label_2.setText(_translate("MainWindow", "Uoo"))
        self.draw.setText(_translate("MainWindow", "二阶电路分析"))
        self.clear.setText(_translate("MainWindow", "清空"))
        self.menu.setTitle(_translate("MainWindow", "帮助"))
        self.actionhelp.setText(_translate("MainWindow", "help"))


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = ThirdWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())